image:
  repository: ghcr.io/mendhak/http-https-echo
  tag: 29
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true

persistence:
  config:
    enabled: true
    emptyDir:
      enabled: true
    mountPath: /www/assets

addons:
  codeserver:
    enabled: true
    git:
      deployKey: test
    workingDir: "/www/assets"
    ingress:
      enabled: true
    volumeMounts:
      - name: config
        mountPath: /www/assets
