controllers:
  main:
    type: cronjob

containers:
  main:
    controller: main
    image:
      repository: ghcr.io/mendhak/http-https-echo
      tag: 29
      pullPolicy: IfNotPresent

service:
  main:
    enabled: false
