containers:
  main:
    controller: main
    image:
      repository: ghcr.io/mendhak/http-https-echo
      tag: 29
      pullPolicy: IfNotPresent

service:
  main:
    controller: main
    ports:
      http:
        port: 8080

ingress:
  main:
    enabled: true

probes:
  liveness:
    enabled: true
  readiness:
    enabled: true
  startup:
    enabled: true

addons:
  netshoot:
    enabled: true
