image:
  repository: ghcr.io/mendhak/http-https-echo
  tag: 29
  pullPolicy: IfNotPresent

service:
  main:
    enabled: false

ingress:
  main:
    enabled: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false
